version: '2'
services:
  zookeeper:
    build: ./zookeeper
    command:
      - "start-foreground"
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_CREATE_TOPICS=customer:1:1,audit:1:1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - JMX_PORT=9999

  kafka-jmx-exporter:
    build: ./prometheus-jmx-exporter 
    ports: 
      - "8080:8080"  
    depends_on:
      - kafka
    environment:
      - JMX_PORT=9999
      - JMX_HOST=kafka
      - HTTP_PORT=8080
      - JMX_EXPORTER_CONFIG_FILE=kafka.yml

  prometheus:
    ports:
      - 9090:9090
    image: prom/prometheus:0.18.0
    volumes:
      - ./mount/prometheus:/etc/prometheus
    depends_on:
      - kafka-jmx-exporter

  grafana:
    image: grafana/grafana:3.0.1
    ports:
      - 3000:3000/tcp
    depends_on:
      - prometheus
    volumes_from:
      - graf-db

  graf-db:
    command:
      - cat
    image: infinityworks/graf-db:08
    depends_on:
      - prometheus
    volumes:
      - /var/lib/grafana/
